"""
People Section Generator  
v0.1

Generates a Markdown file (people.md) containing structured HTML blocks  
for displaying categorized lab and collaborator profiles. Each section includes  
a heading and a responsive grid of profile cards with images, names, titles, and departments.

The layout follows a consistent design pattern and concludes with a 'Check Also' section  
linking to related pages.

Disclaimer:  
This script was 'vibe coded', a lightweight approach to quickly solving a specific need.  
The result has been revised and approved by a human.
"""

import os
from datetime import datetime
from people_data import catalog


# === Date Utility ===

def get_date_str():
    return datetime.now().strftime('%Y-%m-%d %H:%M')

# === Validate Image Files ===

def validate_image_files(catalog, image_dir="./images/people"):
    missing_files = []

    for section_title, people in catalog:
        for person in people:
            img_filename = person["picture"]
            img_path = os.path.join(image_dir, img_filename)
            if not os.path.isfile(img_path):
                missing_files.append((section_title, img_filename))

    return missing_files

# === HTML Generator ===

def generate_html_section(title, people):
    comment_begin = f"<!-- {title} :: BEGIN -->"
    comment_end = f"<!-- {title} :: END -->"

    html = f"\n## {title}\n\n"
    html += f"{comment_begin}\n"
    html += f'<div class="grid-container" data-columns="3">\n\n'

    for person in people:
        html += person_card_template.format(
            picture=person["picture"],
            name=person["name"],
            link=person["link"],
            role_dept=f"{person.get('title', '')}<br/> {person.get('department', '')}".strip(', ')
        )

    html += f'</div>\n{comment_end}\n'
    return html


# === Markdown Header and Footer ===

header = """![GenI-Lab Banner](./images/genilab-banner.png)\n"""
comment = f"""<!-- HTML generated by people.py on {get_date_str()} -->\n"""
footer = """
### Check Also

* [Topics of Interest](./projects.md#topics-of-interest)
* [Tutorials](./knowledge.md#tutorials)
* [Education](./knowledge.md#education)
* [Projects](./projects.md)
* [Resources](./projects.md#resources) 
* [Publications](./knowledge.md#publications)
* [Collaborate](./collaborate.md)
"""

person_card_template = '''  <div class="grid-item person-card">
    <img src="./images/people/{picture}">
    <div class="person-name"><a href="{link}">{name}</a></div>
    <div class="person-title">{role_dept}</div>
  </div>\n\n'''


# === Main Execution Block ===

def main():
    image_dir = "./images/people"
    missing = validate_image_files(catalog, image_dir=image_dir)

    if missing:
        print("❌ Generation aborted -- Missing files!")
        for section, filename in missing:
            print(f"- {filename}")
        exit(1)

    print("✅ All image files found. Proceeding with generation...")

    # Build content
    output = header + "\n" + comment + "\n"
    for section_title, people in catalog:
        output += generate_html_section(section_title, people) + "\n"
    output += footer

    # Write to file
    with open("./people.md", "w", encoding="utf-8") as f:
        f.write(output)

    print("✅ ./people.md generated successfully.")


##
## ENTRY POINT
##

if __name__ == "__main__":
    main()
